In [1]:
import pandas as pd 
import numpy as np
import scipy.stats as stats

In [3]:
data  = pd.read_csv('e-commerce.csv')
data.head()

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
0,101,Female,29,New York,Gold,1120.20,14,4.6,True,25,Satisfied
1,102,Male,34,Los Angeles,Silver,780.50,11,4.1,False,18,Neutral
2,103,Female,43,Chicago,Bronze,510.75,9,3.4,True,42,Unsatisfied
3,104,Male,30,San Francisco,Gold,1480.30,19,4.7,False,12,Satisfied
4,105,Male,27,Miami,Silver,720.40,13,4.0,True,55,Unsatisfied

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               350 non-null    int64
 1   Gender                    350 non-null    object
 2   Age                       350 non-null    int64
 3   City                      350 non-null    object
 4   Membership Type           350 non-null    object
 5   Total Spend               350 non-null    float64
 6   Items Purchased           350 non-null    int64
 7   Average Rating            350 non-null    float64
 8   Discount Applied          350 non-null    bool
 9   Days Since Last Purchase  350 non-null    int64
 10  Satisfaction Level        348 non-null    object
dtypes: bool(1), float64(2), int64(4), object(4)
memory usage: 27.8+ KB

In [5]:
#Dropping missing values
data = data.dropna(subset=['Satisfaction Level'])
data.isnull().sum()

Customer ID                 0
Gender                      0
Age                         0
City                        0
Membership Type             0
Total Spend                 0
Items Purchased             0
Average Rating              0
Discount Applied            0
Days Since Last Purchase    0
Satisfaction Level          0
dtype: int64

In [6]:
data.shape

(348, 11)

In [7]:
data.head()

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
0,101,Female,29,New York,Gold,1120.20,14,4.6,True,25,Satisfied
1,102,Male,34,Los Angeles,Silver,780.50,11,4.1,False,18,Neutral
2,103,Female,43,Chicago,Bronze,510.75,9,3.4,True,42,Unsatisfied
3,104,Male,30,San Francisco,Gold,1480.30,19,4.7,False,12,Satisfied
4,105,Male,27,Miami,Silver,720.40,13,4.0,True,55,Unsatisfied

H0 - All membership type mean spend is the same

H1 - There is a difference in mean spend of membership type

Anova hypothesis testing

In [12]:
from scipy.stats import f_oneway
#filtering the columns of membership types with the total spend column
gold_type = data[data['Membership Type'] == 'Gold']['Total Spend']
silver_type = data[data['Membership Type'] == 'Silver']['Total Spend']
bronze_type = data[data['Membership Type'] == 'Bronze']['Total Spend']
 
 #using one way ANOVA test to verify our hypothesis
anova_statistic,anova_p_value=f_oneway(gold_type,silver_type,bronze_type)
print(anova_p_value)
alpha=0.05
if anova_p_value>alpha:
    print("null hypothesis fails to be rejected thus there is no difference between the means of the membership type spending")
else:
    print("null hypothesis is rejected therefore there is a significant difference in the mean spending of the membership types")

3.744768965836192e-199
null hypothesis is rejected therefore there is a significant difference in the mean spending of the membership types

In [9]:
data.columns

Index(['Customer ID', 'Gender', 'Age', 'City', 'Membership Type',
       'Total Spend', 'Items Purchased', 'Average Rating', 'Discount Applied',
       'Days Since Last Purchase', 'Satisfaction Level'],
      dtype='object')

Chi-square

H0 - Level of satisfaction doesn't differs by gender

H1 - Level of satisfaction differ by gender

In [15]:
data['sex'] = data['Gender'].apply(lambda x: 0 if x=='Female' else 1 )
data['satisfaction_level_new'] = data['Satisfaction Level'].apply(lambda x: 0 if x=='Satisfied' else (1 if x=='Neutral' else 2))
data.head()

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level,sex,satisfaction_level_new
0,101,Female,29,New York,Gold,1120.20,14,4.6,True,25,Satisfied,0,0
1,102,Male,34,Los Angeles,Silver,780.50,11,4.1,False,18,Neutral,1,1
2,103,Female,43,Chicago,Bronze,510.75,9,3.4,True,42,Unsatisfied,0,2
3,104,Male,30,San Francisco,Gold,1480.30,19,4.7,False,12,Satisfied,1,0
4,105,Male,27,Miami,Silver,720.40,13,4.0,True,55,Unsatisfied,1,2

In [26]:
from scipy.stats import chi2_contingency

alpha = 0.05

contigency_table = pd.crosstab(data['Satisfaction Level'], data['Gender'])

chi_statistic,pvalue, degree_of_freedom, expected = chi2_contingency(contigency_table)

print(chi_statistic)

print("The pvalue is:", pvalue)

if pvalue < alpha:
    print('Reject null hypothesis: There is a difference in satisfaction levels')
else:
    print("Fail to reject: Satisfaction level is the same")

0.9046632461007731
The pvalue is: 0.6361431750014872
Fail to reject: Satisfaction level is the same